import { useState } from 'react';
import { Button, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiClient } from '../src/lib/api';
import { Card } from '../src/components/Card';
import { ErrorCard } from '../src/components/ErrorCard';
import { LoadingOverlay } from '../src/components/LoadingOverlay';

const SUGGESTED_QUERIES = [
  'What are the best segments for upselling?',
  'How can we improve customer retention?',
  'Which products should we recommend to premium customers?',
  'What strategies work for budget-conscious customers?',
  'How can we increase spending score?',
];

export default function RecommendationsPage() {
  const [query, setQuery] = useState('What are the best segments for upselling?');
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const onSubmit = async () => {
    if (!query.trim()) {
      setError('Please enter a question');
      return;
    }

    try {
      setLoading(true);
      setError(null);
      const res = await apiClient.recommendations({ query });
      setResult(res);
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Recommendations failed';
      setError(msg);
    } finally {
      setLoading(false);
    }
  };

  const getSourceBadgeColor = (source: string) => {
    return source === 'groq' ? '#8b5cf6' : '#06b6d4';
  };

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>AI Recommendations</Text>
      <Text style={styles.subtitle}>
        Ask questions about your customer segments
      </Text>

      {error && (
        <ErrorCard error={error} onDismiss={() => setError(null)} />
      )}

      <Card>
        <Text style={styles.label}>Your Question</Text>
        <TextInput
          style={[styles.input, styles.textarea]}
          value={query}
          onChangeText={setQuery}
          placeholder="Ask about customer segments, strategies, or recommendations..."
          multiline
          numberOfLines={4}
          editable={!loading}
        />

        <Button
          title={loading ? 'Generating...' : 'Generate Recommendation'}
          onPress={onSubmit}
          disabled={loading}
        />
      </Card>

      {result && (
        <Card variant="success">
          <View style={styles.resultHeader}>
            <Text style={styles.resultTitle}>Recommendation</Text>
            <View
              style={[
                styles.sourceBadge,
                { backgroundColor: getSourceBadgeColor(result.source) },
              ]}
            >
              <Text style={styles.sourceBadgeText}>
                {result.source === 'groq' ? '🤖 AI' : '⚙️ Rules'}
              </Text>
            </View>
          </View>
          <Text style={styles.resultText}>{result.recommendation}</Text>
          {result.source === 'groq' && (
            <Text style={styles.sourceNote}>
              Generated by Groq AI (llama-3.3-70b)
            </Text>
          )}
          {result.source === 'rule_based' && (
            <Text style={styles.sourceNote}>
              Generated from rule-based logic
            </Text>
          )}
        </Card>
      )}

      <Card>
        <Text style={styles.suggestedTitle}>Suggested Questions</Text>
        {SUGGESTED_QUERIES.map((q, idx) => (
          <Button
            key={idx}
            title={q}
            onPress={() => {
              setQuery(q);
              setResult(null);
            }}
            color="#0066cc"
          />
        ))}
      </Card>

      <LoadingOverlay visible={loading} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { padding: 20, gap: 10, backgroundColor: '#f8f9fa' },
  title: { fontSize: 24, fontWeight: '700', marginBottom: 8, color: '#0066cc' },
  subtitle: { fontSize: 14, color: '#666', marginBottom: 16 },
  label: { fontSize: 13, fontWeight: '600', color: '#333', marginBottom: 6 },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#f8f9fa',
    fontSize: 14,
  },
  textarea: { minHeight: 100, textAlignVertical: 'top', marginBottom: 16 },
  resultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  resultTitle: { fontSize: 16, fontWeight: '600', color: '#10b981' },
  sourceBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  sourceBadgeText: { fontSize: 11, fontWeight: '600', color: '#fff' },
  resultText: { fontSize: 14, color: '#333', lineHeight: 20, marginBottom: 12 },
  sourceNote: { fontSize: 11, color: '#999', fontStyle: 'italic' },
  suggestedTitle: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 10 },
});
